-- VHDL Entity tb_lib.tb_basic_alien.symbol
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 15:04:21 08/16/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_basic_alien IS
-- Declarations

END tb_basic_alien ;

--
-- VHDL Architecture tb_lib.tb_basic_alien.struct
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 11:49:51  3.09.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_basic_alien IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk           : std_logic;
   SIGNAL duv_color_out : std_logic_vector(23 DOWNTO 0);
   SIGNAL duv_x_out     : std_logic_vector(7 DOWNTO 0);
   SIGNAL duv_y_out     : std_logic_vector(7 DOWNTO 0);
   SIGNAL en            : std_logic;
   SIGNAL hit           : std_logic;
   SIGNAL rst_n         : std_logic;


   -- Component Declarations
   COMPONENT basic_alien_tester
   PORT (
      duv_color_out : IN     std_logic_vector (23 DOWNTO 0);
      duv_x_out     : IN     std_logic_vector (7 DOWNTO 0);
      duv_y_out     : IN     std_logic_vector (7 DOWNTO 0);
      clk           : OUT    std_logic;
      en            : OUT    std_logic;
      hit           : OUT    std_logic;
      rst_n         : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : basic_alien_tester USE ENTITY tb_lib.basic_alien_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : basic_alien_tester
      PORT MAP (
         duv_x_out     => duv_x_out,
         duv_y_out     => duv_y_out,
         duv_color_out => duv_color_out,
         clk           => clk,
         en            => en,
         rst_n         => rst_n,
         hit           => hit
      );

END struct;
