# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/Hello_LED/Hello_LED.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hello_LED || ORIG_REF_NAME==Hello_LED}]

# IP: bd/Hello_LED/ip/Hello_LED_led_0_0/Hello_LED_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hello_LED_led_0_0 || ORIG_REF_NAME==Hello_LED_led_0_0}]

# XDC: bd/Hello_LED/Hello_LED_ooc.xdc
