# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.cache/wt [current_project]
set_property parent.project_path P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo p:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.srcs/sources_1/bd/Hello_LED/hdl/Hello_LED_wrapper.v
add_files P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.srcs/sources_1/bd/Hello_LED/Hello_LED.bd
set_property used_in_implementation false [get_files -all P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.srcs/sources_1/bd/Hello_LED/Hello_LED_ooc.xdc]
set_property is_locked true [get_files P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.srcs/sources_1/bd/Hello_LED/Hello_LED.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files P:/HLS/Hello_LED/Vivado/Hello_LED/Hello_LED.srcs/constrs_1/new/const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Hello_LED_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef Hello_LED_wrapper.dcp

catch { report_utilization -file Hello_LED_wrapper_utilization_synth.rpt -pb Hello_LED_wrapper_utilization_synth.pb }
