-- VHDL Entity alien_game_lib.alien_game_top.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop10.tuni.fi)
--          at - 00:23:24 11/10/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alien_game_top IS
   PORT( 
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      if_you_name    : OUT    std_logic_vector (7 DOWNTO 0);
      iotre_will     : OUT    std_logic;
      like_this      : OUT    std_logic;
      of_this_course : OUT    std_logic;
      throw_you_out  : OUT    std_logic;
      your_signals   : OUT    std_logic
   );

-- Declarations

END alien_game_top ;

--
-- VHDL Architecture alien_game_lib.alien_game_top.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop2.tuni.fi)
--          at - 18:42:02 11/27/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY pre_made;

ARCHITECTURE struct OF alien_game_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color_bgr_out : std_logic_vector(23 DOWNTO 0);
   SIGNAL frame_done    : std_logic;
   SIGNAL w_rdy         : std_logic;
   SIGNAL write         : std_logic;
   SIGNAL x_coord_out   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord_out   : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT alien_game_logic
   PORT (
      btn           : IN     std_logic_vector (3 DOWNTO 0);
      clk           : IN     std_logic ;
      rst_n         : IN     std_logic ;
      write_ready   : IN     std_logic ;
      color_bgr_out : OUT    std_logic_vector (23 DOWNTO 0);
      frame_done    : OUT    std_logic ;
      write         : OUT    std_logic ;
      x_coord_out   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord_out   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT z_black_box_y
   PORT (
      clk            : IN     std_logic;
      color_BGR      : IN     std_logic_vector (23 DOWNTO 0);
      frame_done     : IN     std_logic;
      rst_n          : IN     std_logic;
      write          : IN     std_logic;
      x_coord        : IN     std_logic_vector (7 DOWNTO 0);
      y_coord        : IN     std_logic_vector (7 DOWNTO 0);
      if_you_name    : OUT    std_logic_vector (7 DOWNTO 0);
      iotre_will     : OUT    std_logic;
      like_this      : OUT    std_logic;
      of_this_course : OUT    std_logic;
      throw_you_out  : OUT    std_logic;
      w_rdy          : OUT    std_logic;
      your_signals   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : alien_game_logic USE ENTITY alien_game_lib.alien_game_logic;
   FOR ALL : z_black_box_y USE ENTITY pre_made.z_black_box_y;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : alien_game_logic
      PORT MAP (
         btn           => btn,
         clk           => clk,
         rst_n         => rst_n,
         write_ready   => w_rdy,
         color_bgr_out => color_bgr_out,
         frame_done    => frame_done,
         write         => write,
         x_coord_out   => x_coord_out,
         y_coord_out   => y_coord_out
      );
   U_0 : z_black_box_y
      PORT MAP (
         clk            => clk,
         color_BGR      => color_bgr_out,
         frame_done     => frame_done,
         rst_n          => rst_n,
         write          => write,
         x_coord        => x_coord_out,
         y_coord        => y_coord_out,
         if_you_name    => if_you_name,
         iotre_will     => iotre_will,
         like_this      => like_this,
         of_this_course => of_this_course,
         throw_you_out  => throw_you_out,
         w_rdy          => w_rdy,
         your_signals   => your_signals
      );

END struct;
