-- VHDL Entity alien_game_lib.c1_t1_half_adder.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop7.tuni.fi)
--          at - 14:38:01 09/18/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t1_half_adder IS
   PORT( 
      sw0   : IN     std_logic;
      sw1   : IN     std_logic;
      carry : OUT    std_logic;
      sum   : OUT    std_logic
   );

-- Declarations

END c1_t1_half_adder ;

--
-- VHDL Architecture alien_game_lib.c1_t1_half_adder.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop7.tuni.fi)
--          at - 14:39:11 09/18/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t1_half_adder IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   carry <= sw0 AND sw1;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   sum <= sw1 XOR sw0;

   -- Instance port mappings.

END struct;
