-- VHDL Entity alien_game_lib.c2_t6_trigger_direction_change.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop8.tuni.fi)
--          at - 16:01:28 10/15/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t6_trigger_direction_change IS
   PORT( 
      x_coord : IN     std_logic_vector (7 DOWNTO 0);
      change  : OUT    std_logic
   );

-- Declarations

END c2_t6_trigger_direction_change ;

--
-- VHDL Architecture alien_game_lib.c2_t6_trigger_direction_change.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop8.tuni.fi)
--          at - 16:01:28 10/15/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t6_trigger_direction_change IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   dout2 <= dout AND x_coord(7);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout1 <= x_coord(0) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout <= '1';

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   change <= dout1 OR dout2;

   -- Instance port mappings.

END struct;
