-- VHDL Entity alien_game_lib.c2_t6_alien_is_hit.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop9.tuni.fi)
--          at - 17:31:28 10/04/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t6_alien_is_hit IS
   PORT( 
      clk            : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      alien_col      : OUT    std_logic_vector (23 DOWNTO 0);
      alien_defeated : OUT    std_logic
   );

-- Declarations

END c2_t6_alien_is_hit ;

--
-- VHDL Architecture alien_game_lib.c2_t6_alien_is_hit.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop2.tuni.fi)
--          at - 18:40:48 11/27/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t6_alien_is_hit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alien_is_defeated : std_logic;
   SIGNAL color_decider     : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout              : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1             : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout4             : std_logic;
   SIGNAL dout5             : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout6             : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL alien_defeated_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic;

   -- Component Declarations
   COMPONENT c6_t2_improved_alien_lives
   PORT (
      clk               : IN     std_logic ;
      hit               : IN     std_logic ;
      rst_n             : IN     std_logic ;
      alien_is_defeated : OUT    std_logic ;
      color_decider     : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_t2_improved_alien_lives USE ENTITY alien_game_lib.c6_t2_improved_alien_lives;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   alien_defeated_internal <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_4reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_4reg_cval <= dout4;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout1 <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout6 <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout5 <= "111111110000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(dout, dout5, dout6, dout1, color_decider)
   BEGIN
      CASE color_decider IS
      WHEN "00" => alien_col <= dout;
      WHEN "01" => alien_col <= dout5;
      WHEN "10" => alien_col <= dout6;
      WHEN "11" => alien_col <= dout1;
      WHEN OTHERS => alien_col <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'or'
   dout4 <= alien_is_defeated OR alien_defeated_internal;

   -- Instance port mappings.
   U_9 : c6_t2_improved_alien_lives
      PORT MAP (
         clk               => clk,
         hit               => hit,
         rst_n             => rst_n,
         alien_is_defeated => alien_is_defeated,
         color_decider     => color_decider
      );

   -- Implicit buffered output assignments
   alien_defeated <= alien_defeated_internal;

END struct;
