-- VHDL Entity alien_game_lib.c2_t6_alien_direction.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop3.tuni.fi)
--          at - 02:36:46 11/23/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t6_alien_direction IS
   PORT( 
      change    : IN     std_logic;
      clk       : IN     std_logic;
      enable    : IN     std_logic;
      rst_n     : IN     std_logic;
      direction : OUT    std_logic
   );

-- Declarations

END c2_t6_alien_direction ;

--
-- VHDL Architecture alien_game_lib.c2_t6_alien_direction.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop3.tuni.fi)
--          at - 02:36:46 11/23/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t6_alien_direction IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1 : std_logic;
   SIGNAL dout : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL direction_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   direction_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(direction_internal, din1, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout <= direction_internal;
      WHEN '1' => dout <= din1;
      WHEN OTHERS => dout <= 'X';
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   din1 <= direction_internal XOR change;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   direction <= direction_internal;

END struct;
