-- VHDL Entity alien_game_lib.c3_t1_gun_module_top.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop9.tuni.fi)
--          at - 15:06:03 11/23/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_gun_module_top IS
   PORT( 
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic;
      enable     : IN     std_logic;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic;
      gun_col    : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord    : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_gun_module_top ;

--
-- VHDL Architecture alien_game_lib.c3_t1_gun_module_top.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop9.tuni.fi)
--          at - 15:06:03 11/23/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t1_gun_module_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout     : std_logic_vector(7 DOWNTO 0);
   SIGNAL q        : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_coord1 : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c3_t1_gun_move
   PORT (
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      x_place : IN     std_logic_vector (7 DOWNTO 0);
      x_coord : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c3_t1_gun_pixel_decider
   PORT (
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      x_in       : IN     std_logic_vector (7 DOWNTO 0);
      x_coord    : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c3_t1_gun_move USE ENTITY alien_game_lib.c3_t1_gun_move;
   FOR ALL : c3_t1_gun_pixel_decider USE ENTITY alien_game_lib.c3_t1_gun_pixel_decider;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   q <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= "00001000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   gun_col <= "100011100000000001001110";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(q, x_coord1, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout <= q;
      WHEN '1' => dout <= x_coord1;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- Instance port mappings.
   U_0 : c3_t1_gun_move
      PORT MAP (
         btn     => btn,
         x_place => q,
         x_coord => x_coord1
      );
   U_1 : c3_t1_gun_pixel_decider
      PORT MAP (
         gun_px_idx => gun_px_idx,
         x_in       => q,
         x_coord    => x_coord,
         y_coord    => y_coord
      );

END struct;
