-- VHDL Entity alien_game_lib.c3_t2_bullet_top.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop1.tuni.fi)
--          at - 14:30:00 10/09/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t2_bullet_top IS
   PORT( 
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic;
      enable      : IN     std_logic;
      gun_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      rst_n       : IN     std_logic;
      color       : OUT    std_logic_vector (23 DOWNTO 0);
      x_out       : OUT    std_logic_vector (7 DOWNTO 0);
      y_out       : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t2_bullet_top ;

--
-- VHDL Architecture alien_game_lib.c3_t2_bullet_top.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop3.tuni.fi)
--          at - 02:41:51 11/23/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t2_bullet_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bullet_flying : std_logic;
   SIGNAL d             : std_logic_vector(7 DOWNTO 0);
   SIGNAL data_out      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout          : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL x_out_internal : std_logic_vector (7 DOWNTO 0);
   SIGNAL y_out_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c3_t2_bullet_move
   PORT (
      btn_fire      : IN     std_logic ;
      y_in          : IN     std_logic_vector (7 DOWNTO 0);
      bullet_flying : OUT    std_logic ;
      y_out         : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c3_t2_bullet_move USE ENTITY alien_game_lib.c3_t2_bullet_move;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   y_out_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   x_out_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= d;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   color <= "000000001010010111111111";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(y_out_internal, data_out, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout <= y_out_internal;
      WHEN '1' => dout <= data_out;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(gun_x_coord, x_out_internal, bullet_flying)
   BEGIN
      CASE bullet_flying IS
      WHEN '0' => d <= gun_x_coord;
      WHEN '1' => d <= x_out_internal;
      WHEN OTHERS => d <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_3 : c3_t2_bullet_move
      PORT MAP (
         btn_fire      => btn(0),
         y_in          => y_out_internal,
         bullet_flying => bullet_flying,
         y_out         => data_out
      );

   -- Implicit buffered output assignments
   x_out <= x_out_internal;
   y_out <= y_out_internal;

END struct;
