-- VHDL Entity alien_game_lib.c5_t1_hit_detector_top.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop5.tuni.fi)
--          at - 14:30:46 11/06/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t1_hit_detector_top IS
   PORT( 
      alien_x  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y : IN     std_logic_vector (7 DOWNTO 0);
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      hit      : OUT    std_logic
   );

-- Declarations

END c5_t1_hit_detector_top ;

--
-- VHDL Architecture alien_game_lib.c5_t1_hit_detector_top.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop5.tuni.fi)
--          at - 15:08:18 11/06/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c5_t1_hit_detector_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1  : std_logic;
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL q     : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout3;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout1 <= dout(7) AND dout(6) AND dout(5) AND dout(4) AND dout(3)
            AND dout(2) AND dout(1) AND dout(0);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout3 <= dout1 AND din1;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   hit <= dout3 AND dout4;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   din1 <= dout2(7) AND dout2(6) AND dout2(5) AND dout2(4) AND dout2(3)
           AND dout2(2) AND dout2(1) AND dout2(0);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'inv'
   dout4 <= NOT(q);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xnor'
   dout <= NOT(alien_x XOR bullet_x);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'xnor'
   dout2 <= NOT(alien_y XOR bullet_y);

   -- Instance port mappings.

END struct;
