-- VHDL Entity alien_game_lib.c6_t2_improved_alien_lives.symbol
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop2.tuni.fi)
--          at - 17:25:21 11/27/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t2_improved_alien_lives IS
   PORT( 
      clk               : IN     std_logic;
      hit               : IN     std_logic;
      rst_n             : IN     std_logic;
      alien_is_defeated : OUT    std_logic;
      color_decider     : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END c6_t2_improved_alien_lives ;

--
-- VHDL Architecture alien_game_lib.c6_t2_improved_alien_lives.struct
--
-- Created:
--          by - kaakkola.kaakkola (linux-desktop2.tuni.fi)
--          at - 17:25:20 11/27/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_t2_improved_alien_lives IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(1 DOWNTO 0);
   SIGNAL sum   : std_logic;
   SIGNAL sum1  : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL alien_is_defeated_internal : std_logic;
   SIGNAL color_decider_internal     : std_logic_vector (1 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic_vector(1 DOWNTO 0);

   -- Component Declarations
   COMPONENT full_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      sw2   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : full_adder USE ENTITY alien_game_lib.full_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   color_decider_internal <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= "00";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= dout2;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'and'
   alien_is_defeated_internal <= color_decider_internal(0)
                                 AND color_decider_internal(1);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout1 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout <= '0';

   -- ModuleWare code(v1.12) for instance 'U_6' of 'merge'
   dout3 <= sum1 & sum;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(dout3, color_decider_internal, 
                          alien_is_defeated_internal)
   BEGIN
      CASE alien_is_defeated_internal IS
      WHEN '0' => dout2 <= dout3;
      WHEN '1' => dout2 <= color_decider_internal;
      WHEN OTHERS => dout2 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- Instance port mappings.
   U_2 : full_adder
      PORT MAP (
         sw0   => color_decider_internal(0),
         sw1   => hit,
         sw2   => dout1,
         carry => carry,
         sum   => sum
      );
   U_4 : full_adder
      PORT MAP (
         sw0   => color_decider_internal(1),
         sw1   => carry,
         sw2   => dout,
         carry => OPEN,
         sum   => sum1
      );

   -- Implicit buffered output assignments
   alien_is_defeated <= alien_is_defeated_internal;
   color_decider     <= color_decider_internal;

END struct;
