-- VHDL Entity alien_game_lib.c7_t4_register_single.symbol
--
-- Created:
--          by - palviain.palviain (linux-desktop2.tuni.fi)
--          at - 16:26:58 12/04/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_t4_register_single IS
   PORT( 
      clk     : IN     std_logic;
      nullify : IN     std_logic;
      pix_d   : IN     std_logic_vector (23 DOWNTO 0);
      rst_n   : IN     std_logic;
      write   : IN     std_logic;
      pix_out : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c7_t4_register_single ;

--
-- VHDL Architecture alien_game_lib.c7_t4_register_single.struct
--
-- Created:
--          by - palviain.palviain (linux-desktop2.tuni.fi)
--          at - 16:26:58 12/04/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_t4_register_single IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din2  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL pix_out_internal : std_logic_vector (23 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(23 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   pix_out_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "000000000000000000000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout1;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   din2 <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(pix_out_internal, pix_d, write)
   BEGIN
      CASE write IS
      WHEN '0' => dout <= pix_out_internal;
      WHEN '1' => dout <= pix_d;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(dout, din2, nullify)
   BEGIN
      CASE nullify IS
      WHEN '0' => dout1 <= dout;
      WHEN '1' => dout1 <= din2;
      WHEN OTHERS => dout1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   pix_out <= pix_out_internal;

END struct;
