-- VHDL Entity alien_game_lib.c7_t2_serial_data_transmit.symbol
--
-- Created:
--          by - palviain.palviain (linux-desktop2.tuni.fi)
--          at - 13:09:48 12/04/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_t2_serial_data_transmit IS
   PORT( 
      bit_in   : IN     std_logic;
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      transmit : IN     std_logic;
      ready    : OUT    std_logic;
      s_clk    : OUT    std_logic;
      s_sda    : OUT    std_logic
   );

-- Declarations

END c7_t2_serial_data_transmit ;

--
-- VHDL Architecture alien_game_lib.c7_t2_serial_data_transmit.fsm
--
-- Created:
--          by - palviain.palviain (linux-desktop2.tuni.fi)
--          at - 13:09:48 12/04/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c7_t2_serial_data_transmit IS

   TYPE STATE_TYPE IS (
      s0,
      s4,
      s1
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(1 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(1 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s4 : std_logic;
   SIGNAL csm_to_s1 : std_logic;

   -- Declare any pre-registered internal signals
   SIGNAL ready_cld : std_logic ;
   SIGNAL s_clk_cld : std_logic ;
   SIGNAL s_sda_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= s0;
         csm_timer <= (OTHERS => '0');
         -- Default Reset Values
         ready_cld <= '1';
         s_clk_cld <= '0';
         s_sda_cld <= '0';
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;

         -- Combined Actions
         CASE current_state IS
            WHEN s0 => 
               IF (transmit = '1') THEN 
                  ready_cld <= '0';
                  s_sda_cld <= bit_in; 
                  s_clk_cld <= '0';
               END IF;
            WHEN s4 => 
               IF (csm_timeout = '1') THEN 
                  ready_cld <= '0';
                  s_clk_cld <= '1';
               END IF;
            WHEN s1 => 
               IF (csm_timeout = '1') THEN 
                  ready_cld <= '1';
                  s_clk_cld <= '0';
                  s_sda_cld <= '0';
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state,
      transmit
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s4 <= '0';
      csm_to_s1 <= '0';
      CASE current_state IS
         WHEN s0 => 
            IF (transmit = '1') THEN 
               next_state <= s4;
               csm_to_s4 <= '1';
            ELSE
               next_state <= s0;
            END IF;
         WHEN s4 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s1;
               csm_to_s1 <= '1';
            ELSE
               next_state <= s4;
            END IF;
         WHEN s1 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s0;
            ELSE
               next_state <= s1;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s4,
      csm_to_s1
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s4 = '1') THEN
         csm_next_timer <= "10"; -- no cycles(3)-1=2
      ELSIF (csm_to_s1 = '1') THEN
         csm_next_timer <= "10"; -- no cycles(3)-1=2
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

   -- Concurrent Statements
   -- Clocked output assignments
   ready <= ready_cld;
   s_clk <= s_clk_cld;
   s_sda <= s_sda_cld;
END fsm;
