set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports input_rsc_dat]
set_property IOSTANDARD LVCMOS33 [get_ports return_rsc_dat]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN M20 [get_ports rst]
set_property PACKAGE_PIN D19 [get_ports input_rsc_dat]
set_property PACKAGE_PIN R14 [get_ports return_rsc_dat]
